nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - ghost

ghost:
  build: ghost
  ports:
    - "2368:2368"
  volumes_from:
    - content

content:
  build: content
  command: echo "Brage ghost blog content volume"
